project_id = "bpytoeulcofbwpyxllku"
[functions.jurisdictions-crud]
enabled = true
verify_jwt = true
import_map = "./functions/jurisdictions-crud/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/jurisdictions-crud/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/jurisdictions-crud/*.html" ]

[functions.licenses-crud]
enabled = true
verify_jwt = true
import_map = "./functions/licenses-crud/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/licenses-crud/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/licenses-crud/*.html" ]
