-- Добавляем начальные статьи в базу данных
INSERT INTO public.blog_posts (
  title_en,
  title_ru,
  content_en,
  content_ru,
  excerpt_en,
  excerpt_ru,
  image_url,
  author,
  category,
  reading_time,
  tags,
  featured,
  color_scheme,
  published,
  created_at,
  updated_at
) VALUES
(
  'Guide to Offshore Company Registration in 2025',
  'Руководство по регистрации оффшорных компаний в 2025 году',
  'Learn about the benefits, procedures, and considerations for registering an offshore company in today''s global business environment.',
  'Узнайте о преимуществах, процедурах и особенностях регистрации оффшорной компании в современной глобальной бизнес-среде.',
  'Learn about the benefits, procedures, and considerations for registering an offshore company in today''s global business environment.',
  'Узнайте о преимуществах, процедурах и особенностях регистрации оффшорной компании в современной глобальной бизнес-среде.',
  'https://images.unsplash.com/photo-1507679799987-c73779587ccf?ixlib=rb-4.0.3&auto=format&fit=crop',
  'Alex Morgan',
  'Company Registration',
  '8 min',
  ARRAY['offshore', 'company registration', 'international business', 'tax optimization'],
  true,
  'blue',
  true,
  NOW(),
  NOW()
),
(
  'Banking Options for International Businesses',
  'Банковские решения для международного бизнеса',
  'Explore the best banking solutions for international businesses, from traditional banks to modern fintech platforms.',
  'Исследуйте лучшие банковские решения для международного бизнеса, от традиционных банков до современных финтех-платформ.',
  'Explore the best banking solutions for international businesses, from traditional banks to modern fintech platforms.',
  'Исследуйте лучшие банковские решения для международного бизнеса, от традиционных банков до современных финтех-платформ.',
  'https://images.unsplash.com/photo-1601597111158-2fceff292cdc?ixlib=rb-4.0.3&auto=format&fit=crop',
  'Sarah Johnson',
  'Banking',
  '6 min',
  ARRAY['international banking', 'business accounts', 'fintech', 'payment solutions'],
  false,
  'orange',
  true,
  NOW(),
  NOW()
),
(
  'Understanding Nominee Services for Your Business',
  'Понимание номинального сервиса для вашего бизнеса',
  'A comprehensive guide to nominee services, including benefits, risks, and regulatory considerations.',
  'Комплексное руководство по номинальным услугам, включая преимущества, риски и нормативные соображения.',
  'A comprehensive guide to nominee services, including benefits, risks, and regulatory considerations.',
  'Комплексное руководство по номинальным услугам, включая преимущества, риски и нормативные соображения.',
  'https://images.unsplash.com/photo-1542744094-24638eff58bb?ixlib=rb-4.0.3&auto=format&fit=crop',
  'Michael Chen',
  'Nominee Services',
  '10 min',
  ARRAY['nominee directors', 'nominee shareholders', 'business confidentiality', 'legal representation'],
  false,
  'graphite',
  true,
  NOW(),
  NOW()
),
(
  'The Complete Guide to Financial Licensing',
  'Полное руководство по финансовому лицензированию',
  'Everything you need to know about obtaining financial licenses in different jurisdictions around the world.',
  'Все, что вам нужно знать о получении финансовых лицензий в различных юрисдикциях по всему миру.',
  'Everything you need to know about obtaining financial licenses in different jurisdictions around the world.',
  'Все, что вам нужно знать о получении финансовых лицензий в различных юрисдикциях по всему миру.',
  'https://images.unsplash.com/photo-1450101499163-c8848c66ca85',
  'Emma Williams',
  'Licensing',
  '12 min',
  ARRAY['financial licenses', 'EMI license', 'regulatory compliance', 'financial institutions'],
  false,
  'blue',
  true,
  NOW(),
  NOW()
),
(
  'Tax Optimization Strategies for Global Businesses',
  'Стратегии налоговой оптимизации для глобального бизнеса',
  'Legal and effective strategies to optimize your tax structure when operating internationally.',
  'Законные и эффективные стратегии оптимизации налоговой структуры при ведении международного бизнеса.',
  'Legal and effective strategies to optimize your tax structure when operating internationally.',
  'Законные и эффективные стратегии оптимизации налоговой структуры при ведении международного бизнеса.',
  'https://images.unsplash.com/photo-1554224155-6726b3ff858f',
  'David Brown',
  'Taxation',
  '9 min',
  ARRAY['tax optimization', 'international taxation', 'tax planning', 'corporate structure'],
  false,
  'orange',
  true,
  NOW(),
  NOW()
),
(
  'Emerging Fintech Trends in 2025',
  'Новые тенденции финтеха в 2025 году',
  'Explore the latest financial technology trends that are reshaping the global business landscape.',
  'Изучите последние тенденции финансовых технологий, которые меняют глобальный бизнес-ландшафт.',
  'Explore the latest financial technology trends that are reshaping the global business landscape.',
  'Изучите последние тенденции финансовых технологий, которые меняют глобальный бизнес-ландшафт.',
  'https://images.unsplash.com/photo-1618044733300-9472054094ee',
  'Jessica Lee',
  'Fintech',
  '7 min',
  ARRAY['fintech', 'digital payments', 'blockchain', 'cryptocurrency'],
  false,
  'graphite',
  true,
  NOW(),
  NOW()
),
(
  'Cryptocurrency Exchange Regulations Worldwide',
  'Регулирование криптовалютных бирж по всему миру',
  'A comprehensive overview of cryptocurrency exchange regulations across different jurisdictions.',
  'Комплексный обзор регулирования криптовалютных бирж в различных юрисдикциях.',
  'A comprehensive overview of cryptocurrency exchange regulations across different jurisdictions.',
  'Комплексный обзор регулирования криптовалютных бирж в различных юрисдикциях.',
  'https://images.unsplash.com/photo-1516245834210-c4c142787335',
  'Robert Zhang',
  'Crypto Licensing',
  '11 min',
  ARRAY['cryptocurrency', 'crypto exchange', 'regulations', 'compliance', 'bitcoin'],
  false,
  'blue',
  true,
  NOW(),
  NOW()
),
(
  'Corporate Restructuring: When and How to Do It Right',
  'Корпоративная реструктуризация: когда и как делать это правильно',
  'Learn about the strategic approaches to corporate restructuring that maximize efficiency and minimize risks.',
  'Узнайте о стратегических подходах к корпоративной реструктуризации, которые максимизируют эффективность и минимизируют риски.',
  'Learn about the strategic approaches to corporate restructuring that maximize efficiency and minimize risks.',
  'Узнайте о стратегических подходах к корпоративной реструктуризации, которые максимизируют эффективность и минимизируют риски.',
  'https://images.unsplash.com/photo-1553877522-43269d4ea984',
  'Thomas Wilson',
  'Corporate Restructuring',
  '10 min',
  ARRAY['corporate restructuring', 'business optimization', 'reorganization', 'mergers and acquisitions'],
  false,
  'orange',
  true,
  NOW(),
  NOW()
); 