-- supabase/migrations/20250504130001_create_licenses_table.sql

create table public.licenses (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer default 0,
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  constraint licenses_name_key unique (name) -- Ensure names are unique
);

-- Optional: Enable Row Level Security (recommended)
alter table public.licenses enable row level security;

-- Optional: Add policies for access control (similar to jurisdictions)
-- create policy "Allow public read access" on public.licenses for select using (true);
-- create policy "Allow authenticated users to manage" on public.licenses for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

-- Trigger to automatically update updated_at timestamp
-- Ensure the moddatetime function exists or the extension is enabled.
-- If using the default Supabase setup, it should be available in extensions schema.
create trigger handle_updated_at before update on public.licenses
  for each row execute procedure extensions.moddatetime (updated_at); 