drop policy "Authenticated users can manage posts" on "public"."blog_posts";

drop policy "Admin can delete blog posts" on "public"."blog_posts";

drop policy "Admin can read all blog posts" on "public"."blog_posts";

create table "public"."contact_requests" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default timezone('utc'::text, now()),
    "name" text,
    "email" text,
    "phone" text,
    "service" text,
    "message" text,
    "status" text default 'unanswered'::text
);


CREATE UNIQUE INDEX contact_requests_pkey ON public.contact_requests USING btree (id);

alter table "public"."contact_requests" add constraint "contact_requests_pkey" PRIMARY KEY using index "contact_requests_pkey";

grant delete on table "public"."contact_requests" to "anon";

grant insert on table "public"."contact_requests" to "anon";

grant references on table "public"."contact_requests" to "anon";

grant select on table "public"."contact_requests" to "anon";

grant trigger on table "public"."contact_requests" to "anon";

grant truncate on table "public"."contact_requests" to "anon";

grant update on table "public"."contact_requests" to "anon";

grant delete on table "public"."contact_requests" to "authenticated";

grant insert on table "public"."contact_requests" to "authenticated";

grant references on table "public"."contact_requests" to "authenticated";

grant select on table "public"."contact_requests" to "authenticated";

grant trigger on table "public"."contact_requests" to "authenticated";

grant truncate on table "public"."contact_requests" to "authenticated";

grant update on table "public"."contact_requests" to "authenticated";

grant delete on table "public"."contact_requests" to "service_role";

grant insert on table "public"."contact_requests" to "service_role";

grant references on table "public"."contact_requests" to "service_role";

grant select on table "public"."contact_requests" to "service_role";

grant trigger on table "public"."contact_requests" to "service_role";

grant truncate on table "public"."contact_requests" to "service_role";

grant update on table "public"."contact_requests" to "service_role";

create policy "Admin can delete blog posts"
on "public"."blog_posts"
as permissive
for delete
to authenticated
using (true);


create policy "Admin can read all blog posts"
on "public"."blog_posts"
as permissive
for select
to authenticated
using (true);



