-- supabase/migrations/20250504130000_create_jurisdictions_table.sql

create table public.jurisdictions (
  id bigint generated by default as identity primary key,
  name text not null,
  sort_order integer default 0,
  is_active boolean default true not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  constraint jurisdictions_name_key unique (name) -- Ensure names are unique
);

-- Optional: Enable Row Level Security (recommended)
alter table public.jurisdictions enable row level security;

-- Optional: Add policies for access control (example: allow public read access)
-- create policy "Allow public read access" on public.jurisdictions for select
-- using (true);

-- Optional: Policy to allow logged-in users (or specific roles) to manage
-- create policy "Allow authenticated users to manage" on public.jurisdictions for all
-- using (auth.role() = 'authenticated') -- Adjust role as needed
-- with check (auth.role() = 'authenticated'); -- Adjust role as needed

-- Trigger to automatically update updated_at timestamp
-- Ensure the moddatetime function exists or the extension is enabled.
-- If using the default Supabase setup, it should be available in extensions schema.
create trigger handle_updated_at before update on public.jurisdictions
  for each row execute procedure extensions.moddatetime (updated_at); 