INSERT INTO public.site_texts (key, section, value_en, value_ru) VALUES
('aboutsection.header.title', 'About Section', 'FintechAssist', 'FintechAssist'),
('aboutsection.header.subtitle', 'About Section', 'UK-based full-service consulting company with deep experience in banking, finance, law, and compliance', 'Британская консалтингово-сервисная компания полного цикла с большим опытом в банковской, финансовой, юридической сфере и комплаенса'),
('aboutsection.card.subtitle', 'About Section', 'Your global fintech partner', 'Ваш глобальный финтех-партнер'),
('aboutsection.card.feature1', 'About Section', 'Personal manager for every client', 'Персональный менеджер для каждого клиента'),
('aboutsection.card.feature2', 'About Section', 'Full support at all stages', 'Полное сопровождение на всех этапах'),
('aboutsection.card.feature3', 'About Section', 'Working through escrow services', 'Работа через сервисы гаранта'),
('aboutsection.card.stat1.label', 'About Section', 'Founded', 'Основано'),
('aboutsection.card.stat2.label', 'About Section', 'Team', 'Команда'),
('aboutsection.card.stat2.unit', 'About Section', 'experts', 'экспертов'),
('aboutsection.card.stat3.label', 'About Section', 'Clients', 'Клиенты'),
('aboutsection.stats.countries.label', 'About Section', 'Countries', 'Стран'),
('aboutsection.stats.clients.label', 'About Section', 'Clients', 'Клиентов'),
('aboutsection.stats.success.label', 'About Section', 'Success Rate', 'Успешных проектов'),
('aboutsection.stats.experience.label', 'About Section', 'Years Experience', 'Лет опыта'),
('aboutsection.buttons.explore', 'About Section', 'Explore Our Services', 'Изучить наши услуги'),
('aboutsection.trustedpartner.title', 'About Section', 'Your Trusted Financial Partner', 'Ваш надежный финансовый партнер'),
('aboutsection.trustedpartner.description', 'About Section', 'Whether you''re a startup or a growing company, we attentively study your goals and demands, developing tailor-made solutions that perfectly align with your needs. We provide a comprehensive range of services, from company registration and account opening to financial licensing and accounting support.', 'Вы старт-ап или развивающаяся компания, мы внимательно выслушаем ваши пожелания и цели, подберем для вас оптимальное индивидуальное решение и реализуем в точности под ваши потребности. Мы предоставляем полный спектр услуг от регистраций компаний и открытия счетов, до получения финансовых лицензий и бухгалтерского обслуживания.'),
('aboutsection.expertise.title', 'About Section', 'Our Expertise', 'Наша экспертиза'),
('aboutsection.expertise.card1.title', 'About Section', 'Company Formation', 'Регистрация компаний'),
('aboutsection.expertise.card1.description', 'About Section', 'We help establish your business entity in various jurisdictions with all necessary documentation.', 'Помогаем зарегистрировать ваш бизнес в различных юрисдикциях со всей необходимой документацией.'),
('aboutsection.expertise.card2.title', 'About Section', 'Financial Licensing', 'Финансовое лицензирование'),
('aboutsection.expertise.card2.description', 'About Section', 'Obtain regulatory approval and financial licenses across multiple international jurisdictions.', 'Получение регуляторных разрешений и финансовых лицензий в различных международных юрисдикциях.'),
('aboutsection.expertise.card3.title', 'About Section', 'Accounting Services', 'Бухгалтерские услуги'),
('aboutsection.expertise.card3.description', 'About Section', 'Professional accounting and financial reporting tailored to your business needs.', 'Профессиональный бухгалтерский учет и финансовая отчетность, адаптированные под потребности вашего бизнеса.'),
('aboutsection.whyus.title', 'About Section', 'Why Choose Us', 'Почему выбирают нас'),
('aboutsection.whyus.card1.title', 'About Section', 'Expert Team', 'Команда экспертов'),
('aboutsection.whyus.card1.description', 'About Section', 'Our team has deep experience in banking, finance, law, and compliance across multiple jurisdictions.', 'Наша команда имеет глубокий опыт в банковской, финансовой, юридической сфере и комплаенсе в различных юрисдикциях.'),
('aboutsection.whyus.card2.title', 'About Section', 'Tailored Solutions', 'Индивидуальные решения'),
('aboutsection.whyus.card2.description', 'About Section', 'We develop custom solutions aligned perfectly with your business goals and specific needs.', 'Мы разрабатываем индивидуальные решения, идеально соответствующие целям и особым потребностям вашего бизнеса.'),
('aboutsection.whyus.card3.title', 'About Section', 'Complete Documentation', 'Полный пакет документов'),
('aboutsection.whyus.card3.description', 'About Section', 'We prepare all necessary documentation, including business plans, AML policies, and application forms.', 'Мы подготовим для вас весь необходимый пакет документов, включая бизнес-план, AML политики, и заполним документы на подачу.'),
('aboutsection.finalcta.title', 'About Section', 'Ready to Transform Your Financial Future?', 'Готовы трансформировать ваше финансовое будущее?'),
('aboutsection.finalcta.description', 'About Section', 'Our team will handle all the necessary documentation, leveraging our years of expertise to ensure a smooth process. Our services are designed to fully meet our clients'' needs in the fintech and financial sectors.', 'Наша команда обработает всю необходимую документацию, используя наш многолетний опыт для обеспечения гладкого процесса. Все наши услуги полностью покрывают потребности клиентов в финтех и финансовой сфере.'),
('aboutsection.buttons.contact', 'About Section', 'Contact Us Today', 'Свяжитесь с нами сегодня')
ON CONFLICT (key) DO NOTHING; -- Prevents errors if keys already exist
