// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bpytoeulcofbwpyxllku.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJweXRvZXVsY29mYndweXhsbGt1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxMDU0NDcsImV4cCI6MjA1ODY4MTQ0N30.DyoafhSBtthQJ4sTdBQ-nuomNauMW5cTOH05D48WdFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);